### ISSUE TITLE
Question Creator Job Posting (Major Feature)

### ISSUE THREAD

**Issue by chn-challenger** [chn-challenger/one_maths#19]
1)  A page where admin can change a user's role from student (default) to **admin** or **creator** via drop down box.

2)  Admin can post/create question-creating jobs in a job board which all creators can view.

3)  Each question-creating job will have an example question, as well as a description with further instructions.

4)  Each creator has access to a staging page where they can test their questions for layout.  And submit the staged questions for admin review.

5)  Admin can see submitted staged questions, can approve and upload them to the database.

and more...

![image](https://cloud.githubusercontent.com/assets/13067624/19976137/7566cbe2-a1e6-11e6-997c-59069bc1f006.png)

![image](https://cloud.githubusercontent.com/assets/13067624/19976152/83e57a56-a1e6-11e6-96ff-70d807624cd3.png)

**Comment by chn-challenger** [comment]
- Make example id not required.
- Make question id visible on questions view.
- Job have images, which are displayed below the description.

**Comment by DXTimer** [comment]
Additions to be made:
- View all jobs as an Admin (Even when they have been taken by a Question_Worker
- Archive jobs as an Admin
- Mark a Job as Complete as a 'question_worker'
- Decouple and delete the test environment from the Questions
- Admin gets Notified when a job has been marked as Complete
